name: Bug report
description: Report a reproducible problem
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Please provide a clear, reproducible report.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened and what did you expect?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include exact steps, inputs, and environment details.
      placeholder: |
        1. Go to ...
        2. Run ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or errors
      render: shell

  - type: input
    id: node
    attributes:
      label: Node.js version
      placeholder: e.g. 20.11.1

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues before opening this report.
          required: true
        - label: I can reproduce this issue on the latest main branch.
          required: true
