name: Feature request
description: Propose a new enhancement
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Share the problem first, then the proposed solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the solution and expected outcome.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What other options were evaluated?

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Who benefits and what changes in workflow?

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I checked existing issues and discussions.
          required: true
        - label: This request is scoped and actionable.
          required: true
